apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: NodePort
  ports:
    - port: 3000         # Port that your application listens on
      targetPort: 3000   # Port in the container
      nodePort: 30001     # Port to access from the host
  selector:
    app: my-app          # Ensure this matches the label of your deployment
