apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: bXlwb3N0Z3Jlcw==  # base64 encoded values
  POSTGRES_PASSWORD: MzMzeHh4  
  POSTGRES_DB: bXlfZHJlYW0=  

